### ISSUE TITLE
Export all galaxies to json file

### ISSUE THREAD

**Issue by sharpninja** [DoubleUTH/DSP-Seed-Finder#1]
Can you add a command line argument that would generate all galaxies and export to a json file?

**Comment by DoubleUTH** [comment]
Well that would be terabytes of data.
To put in perspective, a galaxy takes around 30 KB in RAM. A hundred million seeds mean it would take 3 TB. Convert it to JSON would at least double the size because of overheads. I don't think any program can process a JSON file that big.
